# Generated by Django 5.1.4 on 2025-01-16 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998' bilan boshlanishi va 9 ta raqamdan iborat bo‘lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('soni', models.IntegerField()),
                ('sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narxi', models.IntegerField()),
                ('rasmi', models.URLField()),
                ('malumot', models.TextField()),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
        ),
    ]
